# stages:
#   - build
#   - run

# # DEV DEPLOYMENT (on local GPU server DGX)
# build-dev:
#   stage: build
#   tags: [digital-twin]
#   script:
#     - docker build -t dt-irkg:dev .
#   rules:
#     - if: '$CI_COMMIT_BRANCH == "dev"'

# run-dev:
#   stage: run
#   tags: [digital-twin]
#   script:
#     - docker stop dt-irkg || true
#     - docker rm dt-irkg || true
#     - |
#       docker run -d -e OPENAI_API_KEY="${OPENAI_API_KEY}" \
#        -e SUPPLEMENT_Password="${SUPPLEMENT_Password}" \
#        -e SUPPLEMENT_User="${SUPPLEMENT_User}" \
#        -e SUPPLEMENT_KG_URI="${SUPPLEMENT_KG_URI}" \
#        -e BloodKG_URI="${BloodKG_URI}" \
#        -e MicrobiomeKG_URI="${MicrobiomeKG_URI}" \
#        -p 8010:8000 --name dt-irkg dt-irkg:dev
#   rules:
#     - if: '$CI_COMMIT_BRANCH == "dev"'