# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import protocol_pb2 as protocol__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protocol_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProtocolStub(object):
    """Define the gRPC service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartPrinting = channel.unary_unary(
                '/protocol.Protocol/StartPrinting',
                request_serializer=protocol__pb2.StartPrintingRequest.SerializeToString,
                response_deserializer=protocol__pb2.PrintResponse.FromString,
                _registered_method=True)
        self.StartPrepaireLogoPrinting = channel.unary_unary(
                '/protocol.Protocol/StartPrepaireLogoPrinting',
                request_serializer=protocol__pb2.Empty.SerializeToString,
                response_deserializer=protocol__pb2.PrintResponse.FromString,
                _registered_method=True)
        self.StartManualPrinting = channel.unary_unary(
                '/protocol.Protocol/StartManualPrinting',
                request_serializer=protocol__pb2.StartManualPrintingRequest.SerializeToString,
                response_deserializer=protocol__pb2.PrintResponse.FromString,
                _registered_method=True)
        self.ResetPrinting = channel.unary_unary(
                '/protocol.Protocol/ResetPrinting',
                request_serializer=protocol__pb2.Empty.SerializeToString,
                response_deserializer=protocol__pb2.PrintResponse.FromString,
                _registered_method=True)
        self.CheckPrintingProgress = channel.unary_stream(
                '/protocol.Protocol/CheckPrintingProgress',
                request_serializer=protocol__pb2.Empty.SerializeToString,
                response_deserializer=protocol__pb2.PrintResponse.FromString,
                _registered_method=True)
        self.CalibratePrinter = channel.unary_unary(
                '/protocol.Protocol/CalibratePrinter',
                request_serializer=protocol__pb2.Empty.SerializeToString,
                response_deserializer=protocol__pb2.PrintResponse.FromString,
                _registered_method=True)


class ProtocolServicer(object):
    """Define the gRPC service
    """

    def StartPrinting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartPrepaireLogoPrinting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartManualPrinting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetPrinting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckPrintingProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalibratePrinter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProtocolServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartPrinting': grpc.unary_unary_rpc_method_handler(
                    servicer.StartPrinting,
                    request_deserializer=protocol__pb2.StartPrintingRequest.FromString,
                    response_serializer=protocol__pb2.PrintResponse.SerializeToString,
            ),
            'StartPrepaireLogoPrinting': grpc.unary_unary_rpc_method_handler(
                    servicer.StartPrepaireLogoPrinting,
                    request_deserializer=protocol__pb2.Empty.FromString,
                    response_serializer=protocol__pb2.PrintResponse.SerializeToString,
            ),
            'StartManualPrinting': grpc.unary_unary_rpc_method_handler(
                    servicer.StartManualPrinting,
                    request_deserializer=protocol__pb2.StartManualPrintingRequest.FromString,
                    response_serializer=protocol__pb2.PrintResponse.SerializeToString,
            ),
            'ResetPrinting': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetPrinting,
                    request_deserializer=protocol__pb2.Empty.FromString,
                    response_serializer=protocol__pb2.PrintResponse.SerializeToString,
            ),
            'CheckPrintingProgress': grpc.unary_stream_rpc_method_handler(
                    servicer.CheckPrintingProgress,
                    request_deserializer=protocol__pb2.Empty.FromString,
                    response_serializer=protocol__pb2.PrintResponse.SerializeToString,
            ),
            'CalibratePrinter': grpc.unary_unary_rpc_method_handler(
                    servicer.CalibratePrinter,
                    request_deserializer=protocol__pb2.Empty.FromString,
                    response_serializer=protocol__pb2.PrintResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protocol.Protocol', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('protocol.Protocol', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Protocol(object):
    """Define the gRPC service
    """

    @staticmethod
    def StartPrinting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protocol.Protocol/StartPrinting',
            protocol__pb2.StartPrintingRequest.SerializeToString,
            protocol__pb2.PrintResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartPrepaireLogoPrinting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protocol.Protocol/StartPrepaireLogoPrinting',
            protocol__pb2.Empty.SerializeToString,
            protocol__pb2.PrintResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartManualPrinting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protocol.Protocol/StartManualPrinting',
            protocol__pb2.StartManualPrintingRequest.SerializeToString,
            protocol__pb2.PrintResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetPrinting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protocol.Protocol/ResetPrinting',
            protocol__pb2.Empty.SerializeToString,
            protocol__pb2.PrintResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckPrintingProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/protocol.Protocol/CheckPrintingProgress',
            protocol__pb2.Empty.SerializeToString,
            protocol__pb2.PrintResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalibratePrinter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protocol.Protocol/CalibratePrinter',
            protocol__pb2.Empty.SerializeToString,
            protocol__pb2.PrintResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
