# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocol.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protocol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprotocol.proto\x12\x08protocol\"-\n\x14StartPrintingRequest\x12\x15\n\rcell_quantity\x18\x01 \x01(\x05\"0\n\x1aStartManualPrintingRequest\x12\x12\n\nprint_data\x18\x01 \x01(\t\" \n\rPrintResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xf1\x02\n\x08Protocol\x12H\n\rStartPrinting\x12\x1e.protocol.StartPrintingRequest\x1a\x17.protocol.PrintResponse\x12\x45\n\x19StartPrepaireLogoPrinting\x12\x0f.protocol.Empty\x1a\x17.protocol.PrintResponse\x12T\n\x13StartManualPrinting\x12$.protocol.StartManualPrintingRequest\x1a\x17.protocol.PrintResponse\x12\x39\n\rResetPrinting\x12\x0f.protocol.Empty\x1a\x17.protocol.PrintResponse\x12\x43\n\x15\x43heckPrintingProgress\x12\x0f.protocol.Empty\x1a\x17.protocol.PrintResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTPRINTINGREQUEST']._serialized_start=28
  _globals['_STARTPRINTINGREQUEST']._serialized_end=73
  _globals['_STARTMANUALPRINTINGREQUEST']._serialized_start=75
  _globals['_STARTMANUALPRINTINGREQUEST']._serialized_end=123
  _globals['_PRINTRESPONSE']._serialized_start=125
  _globals['_PRINTRESPONSE']._serialized_end=157
  _globals['_EMPTY']._serialized_start=159
  _globals['_EMPTY']._serialized_end=166
  _globals['_PROTOCOL']._serialized_start=169
  _globals['_PROTOCOL']._serialized_end=538
# @@protoc_insertion_point(module_scope)
