name: Deploy to Local

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy_to_local:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Check SSH connection
        run: |
          echo "Checking SSH connection"
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 20265 dgx@1.tcp.in.ngrok.io "echo 'SSH connection successful'"

      - name: Pull latest changes, install dependencies, and restart app
        run: |
          echo "Pulling latest changes"
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o BatchMode=yes -p 20265 dgx@1.tcp.in.ngrok.io << 'EOF'
            cd /home/dgx/dgx_irkg_be
            git pull origin main
            
            # Install new pip packages
            source venv/bin/activate  # Activate virtual environment (if using one)
            pip install --no-cache-dir -r requirements.txt
            
            # Restart application (modify this based on your setup)
            ./cleanup_uvicorn.sh
          EOF

    environment:
      name: development